package object constants {
  val DiscountIncorrectMsg = "Discount cannot be 0 or negative."
  val DuplicateItemsExistMsg = "Please remove duplicates items from catalog."
  val EmptyString = ""
  val FailedToLoadCatalogMsg = "Failed to load the catalog from the specified path."
  val IllegalInputArgsMsg = "Please specify items you want to buy as program's arguments, e.g.: item1 item2 item3 ..."
  val ItemNameIncorrectMsg = "name cannot contain special characters or be empty."
  val InvalidItemsMsg = "Please check that item(s) name(s), price(s) and special offers as they are incorrect."
  val MergeTwoOverallDiscountsInOneMsg = "Found more than 1 overall discount. Please merge all of them in one or remove unnecessary."
  val Newline = "\n"
  val NoOffers = "(No offers available)"
  val PriceIncorrectMsg = "price cannot be 0 or negative."
  val SupplementItemsIncorrectMsg = "Supplement items in catalog do not exist."
  val RegexOnlyLetters = "^[a-zA-Z]+$"
  val QuantityIncorrectMsg = "Number of supplement items cannot be 0 or negative."
}
